name: main_auth
description: "This package offers a customizable Login and Sign-Up screen for Flutter apps, facilitating integration of forms and social login buttons"

version: 0.0.11
homepage: https://github.com/abdelrahmanghanem
repository: https://github.com/abdelrahmanghanem/main_auth

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  main_button: ^0.0.11
  main_text_field: ^0.0.8
  flutter_svg: ^2.0.10+1
  smart_localize: ^0.0.11
  pinput: ^5.0.0


dev_dependencies:

  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:

  assets:
    - assets/images/
